/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSnackbar: typeof import('./src/components/AppSnackbar.vue')['default']
    BaseDatatable: typeof import('./src/components/BaseDatatable.vue')['default']
    ButtonComponent: typeof import('./src/components/buttonComponent.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    ModalComponent: typeof import('./src/components/modalComponent.vue')['default']
    ModalConfirmation: typeof import('./src/components/modalConfirmation.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
  }
}
